### ISSUE TITLE
OHSU github organization 

### ISSUE THREAD

**Issue by dirkpetersen** [cetola/cetola#1]
Hi there @cetola, we at OHSU IT are trying to take over the Github org https://github.com/ohsu which has been inactive for a dozen years. We were told that you might have created it back then and may be able to assist with moving ownership ? Thanks Dirk

**Comment by cetola** [comment]
Hey @dirkpetersen, looks like one of our research scientists created that account. I've reached out to them to see if they still have access and can help us move it over to OHSU staff. 

I'll let you know if I hear back. If I don't hear back, you can contact GitHub:
https://docs.github.com/en/site-policy/content-removal-policies/github-trademark-policy

They can help you take ownership of the organization based on OHSU's trademark.

**Comment by dirkpetersen** [comment]
Thanks much @cetola , we had reached out to the researcher who created repository lgh-volunteer and they pointed us to you for the organization :) . The trademark policy is a good idea, we had previously failed to achieve anything with Github support.

**Comment by cetola** [comment]
No problem @dirkpetersen, happy to help. That trademark policy is your best bet. GitHub runs into this kind of issue quite a bit where organizations need to acquire their organization from a staff member account where the staff has left the company. If you can't seem to get control of the org through the trademark policy let me know and I'll see if I can connect you with someone at GitHub who can help.
